name = "Sebastian Thies"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Business Central, Dynamics NAV, C#."
company = 'Yaveon'
# company = '<a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>'
#location = "Germany"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
location = "<a href='https://www.google.com/maps/search/Hannover'>Hannover, Germany</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"

[social]
  email = "sebastian.thies@gmx.net"
  #facebook = "yourfacebookusername"
  github = "sebastianthies"
  #twitter = "yourtwitterusername"
  #linkedin = "yourlinkedinusername"